import os
import shutil
from vctube import VCtube

def crawl(youtube_url, lang, name, merge_subtitle, max_time, allowable_distance, skip_autogenerated, max_workers):
    output_dir = f"results/{name}"

    vc = VCtube(
        youtube_url=youtube_url, 
        lang=lang,
        output_dir=output_dir, 
        merge_subtitle=merge_subtitle,
        max_time=max_time,
        allowable_distance=allowable_distance,
        skip_autogenerated=skip_autogenerated,
        max_workers = max_workers
        )

    vc.run()

if __name__ == "__main__":

    YOUTUBE_URL = "ytb.txt"
    LANG = "vi"
    NAME = "test2"

    SKIP_AUTOGENERATED = False
    MERGE_SUBTITLE = True
    MAX_TIME = 30
    ALLOWABLE_DISTANCE = 0.5

    MAX_WORKERS = 4

    crawl(
        youtube_url = YOUTUBE_URL,
        lang=LANG,
        name=NAME,
        merge_subtitle=MERGE_SUBTITLE,
        max_time=MAX_TIME,
        allowable_distance=ALLOWABLE_DISTANCE,
        skip_autogenerated=SKIP_AUTOGENERATED,
        max_workers=MAX_WORKERS
        )

